# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: edd6768229609eb0d53b67e630cb68b3071e61b79c0545befa41517dcd00e3e1d88b8b30b3544919fb6a5714b4e5df437f73a12cbf964499bc8865d5095603ab

test:
  secret_key_base: a0df69f3e01b460bef3f653d2e6794101789855ab7c6c983c765b6ccf8dcecaf1ecd62c30a239ebece40ccd987884305d9a7a8dedd39b224a0da1e30f3634e6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
